apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault-prod
  namespace: vault-prod
spec:
  interval: 10m0s
  chart:
    spec:
      chart: vault
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  values:
    injector:
      enabled: false
    ui:
      enabled: true
    server:
      dev:
        enabled: false
      ha:
        enabled: true
        replicas: 3
        raft:
          enabled: true
          setNodeId: true
          config: |
            ui = true
            listener "tcp" {
              address = "[::]:8200"
              cluster_address = "[::]:8201"
              tls_disable = 1
            }
            storage "raft" {
              path = "/vault/data"
              retry_join {
                leader_api_addr = "http://vault-prod-0.vault-prod-internal:8200"
              }
              retry_join {
                leader_api_addr = "http://vault-prod-1.vault-prod-internal:8200"
              }
              retry_join {
                leader_api_addr = "http://vault-prod-2.vault-prod-internal:8200"
              }
            }
            service_registration "kubernetes" {}
      dataStorage:
        enabled: true
        size: 10Gi
      auditStorage:
        enabled: true
        size: 10Gi
