apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: vpn-pool
  namespace: metallb-system
spec:
  addresses:
    # IPs din subnet-ul intern al node-urilor (192.168.0.x)
    # Verifica in OpenStack Neutron ca aceste IP-uri sunt libere
    # si adauga "allowed address pairs" pe porturile VM-urilor pentru fiecare IP
    - 192.168.0.2-192.168.0.205
