apiVersion: v1
kind: Secret
metadata:
  name: keycloak-external-db
  namespace: platform-identity
type: Opaque
stringData:
  host: keycloak-postgresql.platform-identity.svc.cluster.local
  port: "5432"
  database: keycloak
  username: keycloak
  password: "ChangeMe123!"
