apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-values
  namespace: platform-identity
data:
  values.yaml: |
    fullnameOverride: keycloak
    replicaCount: 1

    keycloak:
      adminUser: admin
      existingSecret: keycloak-admin
      hostname: http://keycloak.licenta.ro
      hostnameStrict: false
      httpEnabled: true
      proxyHeaders: xforwarded
      production: true
      httpRelativePath: /

    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: keycloak.licenta.ro
          paths:
            - path: /
              pathType: Prefix

    service:
      httpPort: 80
      httpTargetPort: 8080

    realm:
      import: true
      configFile: |
        {
          "id": "ZeroTrust-Realm",
          "realm": "ZeroTrust-Realm",
          "displayName": "ZeroTrust Realm",
          "enabled": true,
          "sslRequired": "external",
          "registrationAllowed": false,
          "loginWithEmailAllowed": true,
          "clients": [
            {
              "clientId": "oauth2-proxy",
              "name": "oauth2-proxy",
              "enabled": true,
              "protocol": "openid-connect",
              "publicClient": false,
              "secret": "ChangeMe-OAuth2Proxy-Secret-123",
              "standardFlowEnabled": true,
              "directAccessGrantsEnabled": false,
              "serviceAccountsEnabled": false,
              "implicitFlowEnabled": false,
              "redirectUris": [
                "http://demo.licenta.ro/oauth2/callback"
              ],
              "webOrigins": [
                "http://demo.licenta.ro"
              ],
              "protocolMappers": [
                {
                  "name": "oauth2-proxy-audience",
                  "protocol": "openid-connect",
                  "protocolMapper": "oidc-audience-mapper",
                  "consentRequired": false,
                  "config": {
                    "included.client.audience": "oauth2-proxy",
                    "access.token.claim": "true",
                    "id.token.claim": "true",
                    "userinfo.token.claim": "true"
                  }
                },
                {
                  "name": "groups",
                  "protocol": "openid-connect",
                  "protocolMapper": "oidc-group-membership-mapper",
                  "consentRequired": false,
                  "config": {
                    "claim.name": "groups",
                    "full.path": "false",
                    "access.token.claim": "true",
                    "id.token.claim": "true",
                    "userinfo.token.claim": "true"
                  }
                }
              ]
            }
          ]
        }

    postgres:
      enabled: true
      image:
        tag: "16"
      auth:
        database: keycloak
        username: keycloak
        existingSecret: keycloak-postgres-auth
