apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-values
  namespace: platform-identity
data:
  values.yaml: |
    fullnameOverride: keycloak

    auth:
      adminUser: admin
      adminPassword: "ChangeMe123!"

    proxy: edge
    httpRelativePath: "/"

    extraEnvVars:
      - name: KC_PROXY
        value: edge
      - name: KC_HTTP_ENABLED
        value: "true"
      - name: KC_HOSTNAME
        value: keycloak.licenta.ro
      - name: KC_HOSTNAME_STRICT
        value: "false"
      - name: KC_HOSTNAME_STRICT_HTTPS
        value: "false"

    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: keycloak.licenta.ro
      tls: false
      annotations:
        nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"

    postgresql:
      enabled: true

    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
