apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: monitoring
  labels:
    dashboards: grafana
spec:
  version: "11.5.2"
  deployment:
    spec:
      replicas: 1
      strategy:
        type: Recreate
  config:
    database:
      type: postgres
      host: grafana-postgresql.monitoring.svc.cluster.local:5432
      name: grafana
      user: grafana
      password: CHANGE_ME_GRAFANA_DB_PASSWORD
      ssl_mode: disable
    server:
      root_url: "%(protocol)s://%(domain)s/"
    auth:
      disable_login_form: "false"
    security:
      admin_user: platform_grafana_admin
      admin_password: CHANGE_ME_STRONG_GRAFANA_PASSWORD
    log:
      mode: console
      level: info
    feature_toggles:
      enable: publicDashboards
  service:
    spec:
      type: ClusterIP
