apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tekton-pipeline
  namespace: tekton-pipelines
spec:
  interval: 10m0s
  timeout: 10m0s
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  chart:
    spec:
      chart: tekton-pipeline
      sourceRef:
        kind: HelmRepository
        name: tekton
        namespace: flux-system
  values:
    webhook:
      replicas: 2
