apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-tekton-creds
  namespace: tekton-pipelines
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: oauth2-proxy-tekton-creds
    creationPolicy: Owner
  data:
    - secretKey: OAUTH2_PROXY_CLIENT_ID
      remoteRef:
        key: cicd/tekton-dashboard-oidc
        property: client_id
    - secretKey: OAUTH2_PROXY_CLIENT_SECRET
      remoteRef:
        key: cicd/tekton-dashboard-oidc
        property: client_secret
    - secretKey: OAUTH2_PROXY_COOKIE_SECRET
      remoteRef:
        key: cicd/tekton-dashboard-oidc
        property: cookie_secret
