apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-api-db-secret
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: demo-api-db-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: prod/demo-api/config
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: prod/demo-api/config
        property: password
