apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: istio-system
spec:
  dependsOn:
    - name: istio-base
      namespace: istio-base
  interval: 10m0s
  chart:
    spec:
      chart: cni
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
