apiVersion: v1
kind: Namespace
metadata:
  name: istio-base
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: v1
kind: Namespace
metadata:
  name: istiod
  labels:
    istio-injection: disabled
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-gateway
  labels:
    istio-injection: enabled
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
