apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cosign-keypair
  namespace: test-workload-spire-tekton
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: cosign-keypair
    creationPolicy: Owner
  data:
    - secretKey: cosign.key
      remoteRef:
        key: cicd/cosign
        property: private_key
    - secretKey: cosign.pub
      remoteRef:
        key: cicd/cosign
        property: public_key
    - secretKey: cosign.password
      remoteRef:
        key: cicd/cosign
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-robot-credentials
  namespace: test-workload-spire-tekton
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: harbor-robot-credentials
    creationPolicy: Owner
  data:
    - secretKey: HARBOR_USERNAME
      remoteRef:
        key: cicd/harbor-robot
        property: username
    - secretKey: HARBOR_PASSWORD
      remoteRef:
        key: cicd/harbor-robot
        property: password
