apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - workspace-pvc.yaml
  - service-account-rbac.yaml
  - externalsecrets.yaml
  - spire-clusterspiffeid.yaml
  - peer-authentication.yaml
  - tekton-pipeline.yaml
  - tekton-trigger.yaml
