apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zt-cicd-shared-workspace
  namespace: test-workload-spire-tekton
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
