apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: tekton-operator-chart
  namespace: flux-system
spec:
  interval: 30m0s
  ref:
    tag: v0.79.0
  url: https://github.com/tektoncd/operator.git
