apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cosign-transit-creds
  namespace: test-workload-spire-tekton
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-prod-backend
  target:
    name: cosign-transit-creds
    creationPolicy: Owner
  data:
    - secretKey: VAULT_ADDR
      remoteRef:
        key: cicd/cosign-transit
        property: VAULT_ADDR
    - secretKey: VAULT_TOKEN
      remoteRef:
        key: cicd/cosign-transit
        property: VAULT_TOKEN
    - secretKey: COSIGN_KEY_REF
      remoteRef:
        key: cicd/cosign-transit
        property: COSIGN_KEY_REF
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cosign-pubkey
  namespace: test-workload-spire-tekton
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-prod-backend
  target:
    name: cosign-pubkey
    creationPolicy: Owner
  data:
    - secretKey: cosign.pub
      remoteRef:
        key: cicd/cosign-pubkey
        property: cosign.pub
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-robot-credentials
  namespace: test-workload-spire-tekton
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-prod-backend
  target:
    name: harbor-robot-credentials
    creationPolicy: Owner
  data:
    - secretKey: HARBOR_USERNAME
      remoteRef:
        key: cicd/harbor-project-licenta-robot
        property: username
    - secretKey: HARBOR_PASSWORD
      remoteRef:
        key: cicd/harbor-project-licenta-robot
        property: password
