apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spire
  namespace: spire-system
spec:
  dependsOn:
    - name: spire-postgresql
  interval: 10m0s
  timeout: 10m0s
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  chart:
    spec:
      chart: spire
      sourceRef:
        kind: HelmRepository
        name: spire
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: spire-values
      valuesKey: values.yaml
