apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spire-postgresql
  namespace: spire-system
spec:
  interval: 10m0s
  timeout: 10m0s
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      database: spire
      username: spire
      password: change-me-spire-db-password
    primary:
      persistence:
        enabled: true
        size: 8Gi
