apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-values
  namespace: spire-system
data:
  values.yaml: |
    global:
      spire:
        trustDomain: licenta.local

    spire-server:
      enabled: true
      controllerManager:
        enabled: true
      dataStore:
        sql:
          databaseType: postgres
          databaseName: spire
          host: spire-postgresql.spire-system.svc.cluster.local
          port: 5432
          username: spire
          password: SpireDBPass-2026-Demo
          options:
            - sslmode: disable
      caSubject:
        country: RO
        organization: LICENTA
        caName: SPIRE Server

    spire-agent:
      enabled: true
      socketPath: /run/spire/agent-sockets/spire-agent.sock
      healthChecks:
        enabled: true
