apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aquasecurity-repository.yaml
  - bitnami-repository.yaml
  - bitnami-oci-repository.yaml
  - cloudpirates-oci-repository.yaml
  - oauth2-proxy-repository.yaml
  - istio-repository.yaml
  - falcosecurity-repository.yaml
  - grafana-repository.yaml
  - hashicorp-repository.yaml
  - external-secrets-repository.yaml
  - tf-controller-repository.yaml
  - metallb-repository.yaml
  - ingress-nginx-repository.yaml
  - prometheus-community-repository.yaml
