apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: harbor-storage
  namespace: minio-tenant
spec:
  image: quay.io/minio/minio:RELEASE.2025-02-03T21-03-04Z
  requestAutoCert: false
  mountPath: /export
  users:
    - name: harbor-storage-user
  pools:
    - name: pool-0
      servers: 4
      volumesPerServer: 2
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: local-path
          resources:
            requests:
              storage: 20Gi
