apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../platform/networking
  - ../../platform/mesh
  - ../../platform/observability
  - ../../platform/secrets
  - ../../platform/terraform
  - ../../platform/identity
  - ../../platform/security
  - ../../platform/apps
