apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../platform/platform/platform-networking
  - ../../platform/platform/platform-mesh
  - ../../platform/platform/platform-observability
  - ../../platform/platform/platform-secrets
  - ../../platform/operators/operator-terraform
  - ../../platform/platform/platform-identity
  - ../../platform/platform/platform-security
  - ../../platform/development/dev-apps
