apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: loki-datasource
  namespace: monitoring
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    name: Loki
    uid: loki
    type: loki
    url: http://loki.monitoring:3100
    access: proxy
    isDefault: true
    editable: false
    jsonData:
      maxLines: 5000
      derivedFields: []
