apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: tempo-datasource
  namespace: monitoring
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    name: Tempo
    uid: tempo
    type: tempo
    url: http://tempo.monitoring:3100
    access: proxy
    editable: false
    isDefault: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        tags:
          - key: k8s.namespace.name
            value: namespace
          - key: k8s.pod.name
            value: pod
