apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakOIDCClient
metadata:
  name: oauth2-proxy-client
  namespace: platform-identity
spec:
  keycloakCRName: keycloak
  realm: master-prod
  client:
    clientId: oauth2-proxy
    name: oauth2-proxy
    enabled: true
    protocol: openid-connect
    publicClient: false
    standardFlowEnabled: true
    directAccessGrantsEnabled: false
    serviceAccountsEnabled: true
    redirectUris:
      - https://oauth2-proxy.licenta.ro/oauth2/callback
    webOrigins:
      - https://oauth2-proxy.licenta.ro
