apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: master-prod-realm
  namespace: platform-identity
spec:
  keycloakCRName: keycloak
  realm:
    realm: master-prod
    enabled: true
    displayName: Master Production
    sslRequired: external
    registrationAllowed: false
    loginWithEmailAllowed: true
