apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  interval: 10m0s
  serviceAccountName: oauth2-proxy-reconciler
  timeout: 15m0s
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: oauth2-proxy
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: oauth2-proxy-values
      valuesKey: values.yaml
