apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy-values
  namespace: oauth2-proxy
data:
  values.yaml: |
    replicaCount: 1

    config:
      existingSecret: oauth2-proxy-creds

    extraArgs:
      provider: keycloak-oidc
      http-address: 0.0.0.0:4180
      upstream: static://200
      redirect-url: http://demo.licenta.ro/oauth2/callback
      oidc-issuer-url: http://keycloak.licenta.ro/realms/ZeroTrust-Realm
      email-domain: "*"
      scope: openid profile email groups
      allowed-group: SG_PlatformEngineers
      cookie-secure: "false"
      cookie-httponly: "true"
      cookie-samesite: lax
      session-cookie-minimal: "true"
      set-xauthrequest: "true"
      set-authorization-header: "false"
      pass-access-token: "false"
      pass-user-headers: "true"
      reverse-proxy: "true"
      skip-provider-button: "true"

    service:
      portNumber: 80
