apiVersion: v1
kind: Service
metadata:
  name: platform-prometheus
  namespace: monitoring
spec:
  ports:
    - name: web
      port: 9090
      targetPort: web
  selector:
    operator.prometheus.io/name: platform-prometheus
