apiVersion: v1
kind: Secret
metadata:
  name: ldap-bind-secret
  namespace: platform-day2
type: Opaque
stringData:
  LDAP_BIND_DN: cn=svc_keycloak_bind,ou=ServiceAccounts,dc=licenta,dc=ro
  LDAP_BIND_PASSWORD: P@ssw0rd123!
