apiVersion: v1
kind: Secret
metadata:
  name: keycloak-freeipa-ca
  namespace: platform-identity
type: Opaque
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIEXjCCAsagAwIBAgIRAMkA6zXPUhJKOlkbD8LL+3MwDQYJKoZIhvcNAQELBQAw
    ODEWMBQGA1UECgwNTElDRU5UQS5MT0NBTDEeMBwGA1UEAwwVQ2VydGlmaWNhdGUg
    QXV0aG9yaXR5MB4XDTI2MDQxODE2Mjg0NloXDTQ2MDQxODE2Mjg0NlowODEWMBQG
    A1UECgwNTElDRU5UQS5MT0NBTDEeMBwGA1UEAwwVQ2VydGlmaWNhdGUgQXV0aG9y
    aXR5MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAxYLriQBCK0yiYhR9
    FR9692/SKxNsHmKYlSohvd+BrDUeBnaiRDFlHhKcBj+XpyjAV68UKkYnU7HfV9U+
    HWyRRyq7LdoExT7gApBYK0C0u4yUoAjtP2Ky1fd13uFL/h9tkKMEhMwtXN8ASVXZ
    c1ICheWuEValNXbyln/6XBhkTLVNzirkAMiACmxlSFH8wtYXG1HjzBZlhx1im44I
    OCswGNrH37rjnt4ZkCvpseIDAuX5Zlj9oiXA/IvQluWlVCUqJxtVnVPIQp+4ql5R
    o3Siz/GlCLoSEg7nuEMuUtRG1Gu6GfXhvwQxyC1rPGoc3ncn/qO0/EVzr4bKf6F1
    YE3pfXNk5QJMVpe/vBNSQfRGMDdXXxXjdl9dBOTTeQE3yN299BP56/09Pj+qalB+
    RRKe9M8Db9DwQBZEFo7krSk1UzeTMujxckUKFWt3QK+GSZElyptW8y9bO7ZzlqWx
    8XfScjcaDI6xb/OoLvDvLRByB5ey4Algv62mx0FgEzES4pjbAgMBAAGjYzBhMB0G
    A1UdDgQWBBTz3OlRuwWl1J8ClTgR8IRaWqTgtTAfBgNVHSMEGDAWgBTz3OlRuwWl
    1J8ClTgR8IRaWqTgtTAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBxjAN
    BgkqhkiG9w0BAQsFAAOCAYEAtRFi2kKhM45WzYCF+k7LHgF5qCmAJIphbNiZI8A3
    9x1x3Z6gTR+CtKPk2wPFLq680vSHq5+ic2eSPlatEQwWqUIU4/VzSFbkob0FyQDK
    2isuWO6XVFIhVQT+vUA07M20RE/H1aA44KaJbHIcOR9r+iv/hKuRFxcmLXQrVOtG
    xGJEfXACnXoachsRWNwf7XNn1TfDOIdoyj9qX/bDEyqc05d4fe4agPvfwl8z+uVa
    t/y6tPLTFL9JYdTCFjJ7I6nggCSz9DVTYrLPIYoPPfJKcbBxZWPEZgtoQoyCe8BQ
    GGtrFHC5qFlw2Pk1ZTzhF8V1JUyS72Tc7EtpXJHz8Lj+XY5DFS5YgPdo1zWivNbQ
    h1P2AVVVYyAWXuCFeD7dXOCwmBVq8pZzECcRVJTCSeZZo0rLK37DN+P+qOXQ5LbN
    ahXmetI30BybdOKDn9ixOxL8kn/JfsUuwbAe0GzCxQhVgPW9Sgmq0rgeezKDw2L4
    fTD4wBpsN27MZoXpSdcqTHA6
    -----END CERTIFICATE-----
