apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-builder
  namespace: test-workload-spire-tekton
  labels:
    security.licenta/attested: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-builder
  namespace: test-workload-spire-tekton
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "secrets", "configmaps", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["tekton.dev"]
    resources: ["taskruns", "pipelineruns"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["eventlisteners", "triggerbindings", "triggertemplates", "triggers", "interceptors"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-builder
  namespace: test-workload-spire-tekton
subjects:
  - kind: ServiceAccount
    name: tekton-builder
    namespace: test-workload-spire-tekton
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-builder
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-builder-triggers-read
rules:
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["clusterinterceptors", "clustertriggerbindings"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-builder-triggers-read
subjects:
  - kind: ServiceAccount
    name: tekton-builder
    namespace: test-workload-spire-tekton
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-builder-triggers-read
